@echo off

if defined BUILDKITE_PLUGIN_SKIP_CHECKOUT_CD (
  echo --- Setting checkout directory to %BUILDKITE_PLUGIN_SKIP_CHECKOUT_CD%
  set BUILDKITE_BUILD_CHECKOUT_PATH=%BUILDKITE_PLUGIN_SKIP_CHECKOUT_CD%
)
